import t1 from '../../../../assets/template-01.png';
import t2 from '../../../../assets/template-02.png';
import t3 from '../../../../assets/template-03.png';
import t4 from '../../../../assets/template-04.png';
import t5 from '../../../../assets/template-05.png';
import t6 from '../../../../assets/template-06.png';
import t7 from '../../../../assets/template-07.png';
import t8 from '../../../../assets/template-08.png';

export const TEMPLATE_CATEGORIES = ['All', 'Fashion', 'Jewelry', 'Bags & Accessories', 'Shoes', 'Handmade', 'Home Decor', 'Kids & Baby', 'Gifts'];

export const initialTemplates = [
  {
    id: 'atelier',
    name: 'Atelier',
    author: 'Bloom Studio',
    category: 'Fashion',
    description: 'A premium editorial storefront with refined spacing, rich typography, and a runway-ready hero.',
    demoUrl: 'https://demo.carthive.com/templates/atelier',
    image: t1,
    tags: ['Fashion', 'Editorial', 'Luxury'],
    installed: false,
    active: false,
    favorite: false,
  },
  {
    id: 'pulse',
    name: 'Pulse',
    author: 'Nova Themes',
    category: 'Kids & Baby',
    description: 'High-energy product displays with bold CTA panels and a fast-moving storefront experience.',
    demoUrl: 'https://demo.carthive.com/templates/pulse',
    image: t2,
    tags: ['Electronics', 'Modern', 'Grid'],
    installed: false,
    active: false,
    favorite: false,
  },
  {
    id: 'haven',
    name: 'Haven',
    author: 'Luxe Labs',
    category: 'Home Decor',
    description: 'A calm and luxurious home store layout with large imagery and warm editorial structure.',
    demoUrl: 'https://demo.carthive.com/templates/haven',
    image: t3,
    tags: ['Furniture', 'Calm', 'Lifestyle'],
    installed: false,
    active: false,
    favorite: false,
  },
  {
    id: 'aether',
    name: 'Aether',
    author: 'Fable Themes',
    category: 'Jewelry',
    description: 'Soft gradients, layered imagery, and a spa-inspired product showcase for beauty brands.',
    demoUrl: 'https://demo.carthive.com/templates/aether',
    image: t4,
    tags: ['Beauty', 'Spa', 'Delicate'],
    installed: false,
    active: false,
    favorite: false,
  },
  {
    id: 'mono',
    name: 'Mono',
    author: 'Minimal Works',
    category: 'Bags & Accessories',
    description: 'A clean, airy storefront with neutral palettes, typography-first product storytelling, and elegant whitespace.',
    demoUrl: 'https://demo.carthive.com/templates/mono',
    image: t5,
    tags: ['Minimal', 'Brand', 'Editorial'],
    installed: false,
    active: false,
    favorite: false,
  },
  {
    id: 'lumen',
    name: 'Lumen',
    author: 'Orbit Themes',
    category: 'Gifts',
    description: 'Lifestyle-led homepage layouts with editorial product loops, immersive storytelling blocks, and bold hover interactions.',
    demoUrl: 'https://demo.carthive.com/templates/lumen',
    image: t6,
    tags: ['Lifestyle', 'Editorial', 'Story'],
    installed: false,
    active: false,
    favorite: false,
  },
  {
    id: 'nova',
    name: 'Nova',
    author: 'Polaris Studio',
    category: 'Fashion',
    description: 'A premium boutique experience designed for jewelry, watches, and upscale retail brands.',
    demoUrl: 'https://demo.carthive.com/templates/nova',
    image: t7,
    tags: ['Luxury', 'Boutique', 'Premium'],
    installed: false,
    active: false,
    favorite: false,
  },
  {
    id: 'arcadia',
    name: 'Arcadia',
    author: 'Studio Wren',
    category: 'Handmade',
    description: 'Handmade market vibes with editorial textures, soft accent colors, and rich storytelling sections.',
    demoUrl: 'https://demo.carthive.com/templates/arcadia',
    image: t8,
    tags: ['Artisan', 'Warm', 'Craft'],
    installed: false,
    active: false,
    favorite: false,
  }
];
