import heroImg from '../../../../assets/hero-img.avif';
import bannerImg from '../../../../assets/banner.avif';
import categoryBracelet from '../../../../assets/category-bracelet.jpg';
import categoryChain from '../../../../assets/category-chain.jpg';
import categoryEaring from '../../../../assets/category-earing.avif';
import categoryRing from '../../../../assets/category-ring.jpg';

export const TEMPLATE_CATEGORIES = ['All', 'Fashion', 'Electronics', 'Furniture', 'Beauty', 'Minimal', 'Lifestyle', 'Luxury', 'Artisan'];

export const initialTemplates = [
  {
    id: 'atelier',
    name: 'Atelier',
    store_name: 'Atelier Studio',
    author: 'Bloom Studio',
    category: 'Fashion',
    description: 'A premium editorial storefront with refined spacing and runway-ready style.',
    demoUrl: '/admin/templates/preview/atelier',
    image: categoryEaring,
    hero_image: heroImg,
    hero_heading: 'Refined fashion for modern wardrobes',
    hero_subtext: 'A curated storefront experience for elevated apparel brands.',
    banner_image: bannerImg,
    banner_title: 'Seasonal runway collections',
    banner_subtitle: 'Explore timeless silhouettes and editorial looks.',
    ticker_text: 'NEW ARRIVALS: limited edition styles • free shipping over $150 •',
    support_email: 'support@atelierstudio.com',
    support_phone: '+1 800 555 0143',
    physical_address: '248 Fashion Ave, New York, NY',
    footer_about: 'Atelier Studio brings fashion editorial energy to your online storefront with premium visuals and sleek product storytelling.',
    instagram_link: 'https://instagram.com/atelierstudio',
    terms_and_conditions: 'By using Atelier Studio, you agree to our terms and conditions. All rights reserved.',
    privacy_policy: 'We respect your privacy and only use your information to improve your shopping experience.',
    shipping_policy: 'Orders are shipped within 3 business days. Tracking details are emailed upon dispatch.',
    refund_policy: 'Returns are accepted within 30 days in original condition. Contact support to start a refund.',
    tags: ['Fashion', 'Editorial', 'Luxury'],
    installed: false,
    active: false,
    favorite: false,
  },
  {
    id: 'pulse',
    name: 'Pulse',
    store_name: 'Pulse Gear',
    author: 'Nova Themes',
    category: 'Electronics',
    description: 'High-energy product displays with bold CTA panels and fast-moving storefront motion.',
    demoUrl: '/admin/templates/preview/pulse',
    image: categoryChain,
    hero_image: heroImg,
    hero_heading: 'Bold electronics for energetic brands',
    hero_subtext: 'Showcase tech products with high-impact visuals and a modern retail feel.',
    banner_image: bannerImg,
    banner_title: 'Power up your storefront',
    banner_subtitle: 'Launch new collections with striking imagery and bold layout.',
    ticker_text: 'HOT DEALS: new gadgets, free delivery on orders over $100, limited stock •',
    support_email: 'support@pulselabs.com',
    support_phone: '+1 800 555 0267',
    physical_address: '312 Innovation Dr, San Francisco, CA',
    footer_about: 'Pulse Gear is crafted for dynamic electronics stores that need sharp design and fast product discovery.',
    instagram_link: 'https://instagram.com/pulselabs',
    terms_and_conditions: 'Customer purchases are governed by our standard terms and conditions and return policy.',
    privacy_policy: 'Your data is protected and used only to provide a better shopping experience.',
    shipping_policy: 'Shipping is calculated at checkout. Expect 3-5 business days for delivery.',
    refund_policy: 'If you are not satisfied, returns are accepted within 30 days with proof of purchase.',
    tags: ['Electronics', 'Modern', 'Grid'],
    installed: false,
    active: false,
    favorite: false,
  },
  {
    id: 'haven',
    name: 'Haven',
    store_name: 'Haven Home',
    author: 'Luxe Labs',
    category: 'Furniture',
    description: 'A calm and luxurious home store layout with large imagery and warm editorial structure.',
    demoUrl: '/admin/templates/preview/haven',
    image: categoryBracelet,
    hero_image: heroImg,
    hero_heading: 'Serene interiors for elevated living',
    hero_subtext: 'A luxurious furniture showcase designed to inspire calm, curated spaces.',
    banner_image: bannerImg,
    banner_title: 'Design your sanctuary',
    banner_subtitle: 'Explore elegant home collections and soothing lifestyle accents.',
    ticker_text: 'INSIDE LOOK: new home arrivals • free white glove delivery •',
    support_email: 'support@havenhome.com',
    support_phone: '+1 800 555 0341',
    physical_address: '798 Oak Street, Austin, TX',
    footer_about: 'Haven Home blends warm visuals with premium product storytelling for upscale furniture brands.',
    instagram_link: 'https://instagram.com/havenhome',
    terms_and_conditions: 'All sales are subject to our terms and conditions. Please read carefully before purchase.',
    privacy_policy: 'We safeguard your personal data and never share it with third parties without consent.',
    shipping_policy: 'Standard shipping takes 4-7 business days. Expedited options are available at checkout.',
    refund_policy: 'Returns are accepted within 30 days. Furniture must be returned in original packaging.',
    tags: ['Furniture', 'Calm', 'Lifestyle'],
    installed: false,
    active: false,
    favorite: false,
  },
  {
    id: 'aether',
    name: 'Aether',
    store_name: 'Aether Beauty',
    author: 'Fable Themes',
    category: 'Beauty',
    description: 'Soft gradients, layered imagery, and a spa-inspired product showcase for beauty brands.',
    demoUrl: '/admin/templates/preview/aether',
    image: categoryRing,
    hero_image: heroImg,
    hero_heading: 'Beauty rituals with a calming editorial feel',
    hero_subtext: 'A spa-inspired online storefront built for wellness and self-care brands.',
    banner_image: bannerImg,
    banner_title: 'Nourish your glow',
    banner_subtitle: 'Discover refined beauty collections and calming product displays.',
    ticker_text: 'SPA FAVORITES: new skincare launches • free samples on orders above $75 •',
    support_email: 'support@aetherbeauty.com',
    support_phone: '+1 800 555 0482',
    physical_address: '421 Bloom Ave, Los Angeles, CA',
    footer_about: 'Aether Beauty creates an immersive wellness storefront with soft imagery and thoughtful product arrangement.',
    instagram_link: 'https://instagram.com/aetherbeauty',
    terms_and_conditions: 'Please review our terms and conditions before ordering. We value transparency and care.',
    privacy_policy: 'Your privacy is important. We only collect necessary information to process orders.',
    shipping_policy: 'Orders ship within 3 business days. Expect standard delivery in 5-8 business days.',
    refund_policy: 'Returns accepted within 30 days when products are returned in original condition.',
    tags: ['Beauty', 'Spa', 'Delicate'],
    installed: false,
    active: false,
    favorite: false,
  },
  {
    id: 'mono',
    name: 'Mono',
    store_name: 'Mono Studio',
    author: 'Minimal Works',
    category: 'Minimal',
    description: 'A clean, airy storefront with neutral palettes, typography-first product storytelling, and elegant whitespace.',
    demoUrl: '/admin/templates/preview/mono',
    image: categoryRing,
    hero_image: heroImg,
    hero_heading: 'Minimal design with bold brand clarity',
    hero_subtext: 'A refined shopping experience for brands that value calm, modern simplicity.',
    banner_image: bannerImg,
    banner_title: 'Less is more',
    banner_subtitle: 'Simple product layouts, strong typography, and premium spacing.',
    ticker_text: 'NEW ARRIVALS: contemporary essentials • free shipping on orders over $100 •',
    support_email: 'support@monostudio.com',
    support_phone: '+1 800 555 0593',
    physical_address: '504 Ninth St, Chicago, IL',
    footer_about: 'Mono Studio offers clean retail presentation with high-end editorial visuals and elegant spacing.',
    instagram_link: 'https://instagram.com/monostudio',
    terms_and_conditions: 'By using Mono Studio, you agree to our store terms and checkout policies.',
    privacy_policy: 'We respect your privacy and handle your information securely as part of your shopping journey.',
    shipping_policy: 'Free shipping applies to orders over $100. Delivery normally takes 4-6 business days.',
    refund_policy: 'Refunds available within 30 days, subject to product condition and order verification.',
    tags: ['Minimal', 'Brand', 'Editorial'],
    installed: false,
    active: false,
    favorite: false,
  },
  {
    id: 'lumen',
    name: 'Lumen',
    store_name: 'Lumen Living',
    author: 'Orbit Themes',
    category: 'Lifestyle',
    description: 'Lifestyle-led homepage layouts with editorial product loops, immersive storytelling blocks, and bold hover interactions.',
    demoUrl: '/admin/templates/preview/lumen',
    image: categoryBracelet,
    hero_image: heroImg,
    hero_heading: 'Lifestyle products presented with cinematic flair',
    hero_subtext: 'A captivating storefront for modern lifestyle and home brands.',
    banner_image: bannerImg,
    banner_title: 'Live inspired',
    banner_subtitle: 'Explore elevated collections and storytelling-driven shopping.',
    ticker_text: 'TRENDING NOW: lifestyle essentials • free delivery on select items •',
    support_email: 'support@lumenliving.com',
    support_phone: '+1 800 555 0664',
    physical_address: '672 Westwood Blvd, Seattle, WA',
    footer_about: 'Lumen Living blends immersive lifestyle visuals with strong product storytelling and premium editorial style.',
    instagram_link: 'https://instagram.com/lumenliving',
    terms_and_conditions: 'These terms and conditions govern your purchase and use of the Lumen Living storefront.',
    privacy_policy: 'We protect your personal data and use it only to deliver a better shopping experience.',
    shipping_policy: 'Standard order shipping takes 5-7 business days. Expedited delivery options available.',
    refund_policy: 'Refunds are offered within 30 days for eligible purchases returned in original packaging.',
    tags: ['Lifestyle', 'Editorial', 'Story'],
    installed: false,
    active: false,
    favorite: false,
  },
  {
    id: 'nova',
    name: 'Nova',
    store_name: 'Nova Boutique',
    author: 'Polaris Studio',
    category: 'Luxury',
    description: 'A premium boutique experience designed for jewelry, watches, and upscale retail brands.',
    demoUrl: '/admin/templates/preview/nova',
    image: categoryChain,
    hero_image: heroImg,
    hero_heading: 'Luxury storefronts for elegant brands',
    hero_subtext: 'A boutique retail presentation designed for premium products and refined customers.',
    banner_image: bannerImg,
    banner_title: 'Shop luxury essentials',
    banner_subtitle: 'Discover exquisitely crafted collections and signature pieces.',
    ticker_text: 'PREMIUM EDITION: curated selections • white glove delivery available •',
    support_email: 'support@novaboutique.com',
    support_phone: '+1 800 555 0775',
    physical_address: '910 Grand Blvd, Beverly Hills, CA',
    footer_about: 'Nova Boutique offers an elegant retail experience with high-end visuals and luxury product storytelling.',
    instagram_link: 'https://instagram.com/novaboutique',
    terms_and_conditions: 'All purchases are bound by our terms and conditions, including returns and shipping policies.',
    privacy_policy: 'Your privacy is important. We use your data only for order fulfillment and store improvements.',
    shipping_policy: 'Luxury shipping services available. Standard delivery typically arrives in 4-7 business days.',
    refund_policy: 'Refunds can be requested within 30 days for eligible luxury items in original condition.',
    tags: ['Luxury', 'Boutique', 'Premium'],
    installed: false,
    active: false,
    favorite: false,
  },
  {
    id: 'arcadia',
    name: 'Arcadia',
    store_name: 'Arcadia Market',
    author: 'Studio Wren',
    category: 'Artisan',
    description: 'Handmade market vibes with editorial textures, soft accent colors, and rich storytelling sections.',
    demoUrl: '/admin/templates/preview/arcadia',
    image: categoryRing,
    hero_image: heroImg,
    hero_heading: 'Artisan goods for hand-crafted brands',
    hero_subtext: 'A warm, story-rich storefront built for makers and craft-driven shops.',
    banner_image: bannerImg,
    banner_title: 'Crafted collections',
    banner_subtitle: 'Explore artisan pieces and authentic handcrafted goods.',
    ticker_text: 'HANDMADE: new artisan releases • shop ethical, shop local •',
    support_email: 'support@arcadiamarket.com',
    support_phone: '+1 800 555 0886',
    physical_address: '143 Market Lane, Portland, OR',
    footer_about: 'Arcadia Market brings handcrafted goods to life with warm visuals, textured layouts, and rich storytelling.',
    instagram_link: 'https://instagram.com/arcadiamarket',
    terms_and_conditions: 'Review our terms and conditions before completing your purchase.',
    privacy_policy: 'We respect your privacy and keep your information secure and confidential.',
    shipping_policy: 'Standard shipping is 4-7 business days. Handmade items may require additional processing time.',
    refund_policy: 'Refunds are accepted within 30 days for handcrafted items returned in original condition.',
    tags: ['Artisan', 'Warm', 'Craft'],
    installed: false,
    active: false,
    favorite: false,
  }
];
